# Generated by Django 4.2.4 on 2023-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=250)),
                ('joindate', models.DateTimeField()),
                ('koment', models.IntegerField()),
            ],
        ),
    ]
